title: fortune-teller-cc
hero_image: images/banner.png
description: fortune-teller-cc description
version: 4
listed: false
copyedit: false
last_tested: "2019-08-21"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
